/**
 * Data-driven definition of the mannequin: a skeleton of joints (bones) and a
 * set of muscle overlays attached to those bones. Everything is plain data so
 * the figure can be rebuilt, tuned, or inspected without touching render code.
 *
 * Conventions
 * -----------
 * - Units are meters, Y is up, the figure faces +Z, its **left** side is +X.
 * - Each bone is a group whose origin sits at its proximal joint. Limb meshes
 *   extend down the local -Y axis, so the neutral build (all rotations 0) is a
 *   figure standing upright with arms at its sides.
 */

export type BoneShape = "capsule" | "box" | "sphere";

export interface BoneDef {
  readonly name: string;
  readonly parent: string | null;
  /** Offset from the parent joint origin, in the parent's local frame. */
  readonly offset: readonly [number, number, number];
  readonly shape: BoneShape;
  /** Capsule: segment length down -Y. */
  readonly length?: number;
  /** Capsule/sphere radius. */
  readonly radius?: number;
  /** Box half-extents are size/2. */
  readonly size?: readonly [number, number, number];
  /** Optional offset of the mesh within the bone group. */
  readonly meshOffset?: readonly [number, number, number];
}

/** Base id of a muscle group (side-agnostic; used when authoring exercises). */
export type MuscleId =
  | "quadriceps"
  | "hamstrings"
  | "adductors"
  | "gluteus"
  | "calves"
  | "pectoral"
  | "latissimus"
  | "trapezius"
  | "deltoid"
  | "biceps"
  | "triceps"
  | "forearm"
  | "abdominals"
  | "erector_spinae";

export type MuscleRegion = "legs" | "back" | "chest" | "shoulders" | "arms" | "core";

interface MuscleDef {
  readonly id: MuscleId;
  /** Bone (base name) the muscle is attached to. */
  readonly parent: string;
  /** Whether the parent bone itself is sided (gets an L/R suffix). */
  readonly parentSided: boolean;
  /** Whether to create mirrored L/R copies of the muscle. */
  readonly sided: boolean;
  /** Offset within the (left) parent bone's local frame. */
  readonly offset: readonly [number, number, number];
  /** Ellipsoid radii of the muscle bulge. */
  readonly size: readonly [number, number, number];
}

export interface MuscleInstance {
  /** Unique instance name, e.g. "quadriceps_L". */
  readonly name: string;
  /** Side-agnostic group id, e.g. "quadriceps". */
  readonly id: MuscleId;
  /** Exact bone name this instance attaches to, e.g. "hipL". */
  readonly bone: string;
  readonly offset: readonly [number, number, number];
  readonly size: readonly [number, number, number];
}

export interface MuscleInfo {
  readonly label: string;
  readonly region: MuscleRegion;
}

/** Human-friendly labels (English + Korean) and regions, keyed by base id. */
export const MUSCLE_INFO: Record<MuscleId, MuscleInfo> = {
  quadriceps: { label: "Quadriceps · 대퇴사두근", region: "legs" },
  hamstrings: { label: "Hamstrings · 햄스트링", region: "legs" },
  adductors: { label: "Adductors · 내전근", region: "legs" },
  gluteus: { label: "Gluteus · 둔근", region: "legs" },
  calves: { label: "Calves · 종아리", region: "legs" },
  pectoral: { label: "Pectorals · 대흉근", region: "chest" },
  latissimus: { label: "Latissimus · 광배근", region: "back" },
  trapezius: { label: "Trapezius · 승모근", region: "back" },
  deltoid: { label: "Deltoids · 삼각근", region: "shoulders" },
  biceps: { label: "Biceps · 이두근", region: "arms" },
  triceps: { label: "Triceps · 삼두근", region: "arms" },
  forearm: { label: "Forearms · 전완근", region: "arms" },
  abdominals: { label: "Abdominals · 복근", region: "core" },
  erector_spinae: { label: "Erector spinae · 척추기립근", region: "core" },
};

// ---------------------------------------------------------------------------
// Skeleton
// ---------------------------------------------------------------------------

/** Central (non-sided) bones along the spine. */
const CENTRAL_BONES: BoneDef[] = [
  { name: "pelvis", parent: null, offset: [0, 0.955, 0], shape: "box", size: [0.3, 0.16, 0.19] },
  { name: "spine", parent: "pelvis", offset: [0, 0.14, 0], shape: "box", size: [0.26, 0.2, 0.16], meshOffset: [0, 0.02, 0] },
  { name: "chest", parent: "spine", offset: [0, 0.18, 0], shape: "box", size: [0.34, 0.24, 0.19], meshOffset: [0, 0.02, 0] },
  { name: "neck", parent: "chest", offset: [0, 0.18, 0], shape: "capsule", length: 0.1, radius: 0.05 },
  { name: "head", parent: "neck", offset: [0, 0.1, 0], shape: "sphere", radius: 0.12, meshOffset: [0, 0.08, 0] },
];

/**
 * Sided bone templates (the left side). The right side is generated by
 * mirroring the X offset. `parentSided` controls whether the parent name also
 * gets an L/R suffix.
 */
interface SidedBoneTemplate {
  readonly base: string;
  readonly parent: string;
  readonly parentSided: boolean;
  readonly offset: readonly [number, number, number];
  readonly shape: BoneShape;
  readonly length?: number;
  readonly radius?: number;
  readonly size?: readonly [number, number, number];
  readonly meshOffset?: readonly [number, number, number];
}

const SIDED_BONES: SidedBoneTemplate[] = [
  // Arms
  { base: "shoulder", parent: "chest", parentSided: false, offset: [0.19, 0.16, 0], shape: "capsule", length: 0.3, radius: 0.05 },
  { base: "elbow", parent: "shoulder", parentSided: true, offset: [0, -0.3, 0], shape: "capsule", length: 0.27, radius: 0.045 },
  { base: "wrist", parent: "elbow", parentSided: true, offset: [0, -0.27, 0], shape: "box", size: [0.06, 0.18, 0.1], meshOffset: [0, -0.07, 0.01] },
  // Legs
  { base: "hip", parent: "pelvis", parentSided: false, offset: [0.1, -0.06, 0], shape: "capsule", length: 0.45, radius: 0.085 },
  { base: "knee", parent: "hip", parentSided: true, offset: [0, -0.45, 0], shape: "capsule", length: 0.41, radius: 0.06 },
  { base: "ankle", parent: "knee", parentSided: true, offset: [0, -0.41, 0], shape: "box", size: [0.1, 0.07, 0.26], meshOffset: [0, 0.0, 0.08] },
];

function mirrorX(o: readonly [number, number, number]): [number, number, number] {
  return [-o[0], o[1], o[2]];
}

/** Fully expanded list of bones (central + L/R sided), parents before children. */
export const BONES: BoneDef[] = (() => {
  const out: BoneDef[] = [...CENTRAL_BONES];
  for (const side of ["L", "R"] as const) {
    for (const t of SIDED_BONES) {
      const parent = t.parentSided ? `${t.parent}${side}` : t.parent;
      const offset = side === "L" ? t.offset : mirrorX(t.offset);
      out.push({
        name: `${t.base}${side}`,
        parent,
        offset,
        shape: t.shape,
        length: t.length,
        radius: t.radius,
        size: t.size,
        meshOffset: t.meshOffset,
      });
    }
  }
  return out;
})();

// ---------------------------------------------------------------------------
// Muscles
// ---------------------------------------------------------------------------

const MUSCLE_DEFS: MuscleDef[] = [
  // Legs
  { id: "quadriceps", parent: "hip", parentSided: true, sided: true, offset: [0, -0.22, 0.06], size: [0.07, 0.21, 0.045] },
  { id: "hamstrings", parent: "hip", parentSided: true, sided: true, offset: [0, -0.24, -0.06], size: [0.07, 0.21, 0.045] },
  { id: "adductors", parent: "hip", parentSided: true, sided: true, offset: [-0.045, -0.2, 0.01], size: [0.04, 0.18, 0.05] },
  { id: "calves", parent: "knee", parentSided: true, sided: true, offset: [0, -0.16, -0.05], size: [0.05, 0.15, 0.04] },
  { id: "gluteus", parent: "pelvis", parentSided: false, sided: true, offset: [0.09, -0.04, -0.1], size: [0.1, 0.1, 0.08] },
  // Torso / core
  { id: "abdominals", parent: "spine", parentSided: false, sided: false, offset: [0, 0.02, 0.09], size: [0.12, 0.16, 0.04] },
  { id: "erector_spinae", parent: "spine", parentSided: false, sided: false, offset: [0, 0.02, -0.085], size: [0.13, 0.17, 0.035] },
  // Back / chest / shoulders
  { id: "pectoral", parent: "chest", parentSided: false, sided: true, offset: [0.07, 0.05, 0.1], size: [0.09, 0.08, 0.05] },
  { id: "latissimus", parent: "chest", parentSided: false, sided: true, offset: [0.13, -0.04, -0.03], size: [0.05, 0.15, 0.08] },
  { id: "trapezius", parent: "chest", parentSided: false, sided: false, offset: [0, 0.15, -0.04], size: [0.2, 0.09, 0.06] },
  { id: "deltoid", parent: "shoulder", parentSided: true, sided: true, offset: [0, 0.01, 0], size: [0.07, 0.08, 0.075] },
  // Arms
  { id: "biceps", parent: "shoulder", parentSided: true, sided: true, offset: [0, -0.15, 0.045], size: [0.045, 0.12, 0.04] },
  { id: "triceps", parent: "shoulder", parentSided: true, sided: true, offset: [0, -0.15, -0.045], size: [0.045, 0.13, 0.04] },
  { id: "forearm", parent: "elbow", parentSided: true, sided: true, offset: [0, -0.13, 0.0], size: [0.04, 0.13, 0.04] },
];

/** Expand muscle definitions into concrete per-side instances. */
export const MUSCLES: MuscleInstance[] = (() => {
  const out: MuscleInstance[] = [];
  for (const m of MUSCLE_DEFS) {
    if (m.sided) {
      for (const side of ["L", "R"] as const) {
        const bone = m.parentSided ? `${m.parent}${side}` : m.parent;
        const offset = side === "L" ? [...m.offset] as [number, number, number] : mirrorX(m.offset);
        out.push({ name: `${m.id}_${side}`, id: m.id, bone, offset, size: m.size });
      }
    } else {
      out.push({ name: m.id, id: m.id, bone: m.parent, offset: [...m.offset] as [number, number, number], size: m.size });
    }
  }
  return out;
})();

/** All distinct muscle group ids, in a stable display order. */
export const MUSCLE_IDS: MuscleId[] = Object.keys(MUSCLE_INFO) as MuscleId[];
